### ISSUE TITLE
NETWORK_ERR: XMLHttpRequest Exception 101

### ISSUE THREAD

**Issue by pziemkowski** [sdimkov/hubot-skype-web#17] opened 2016-01-11 09:33 UTC
I am trying to run hubot-skype-web on ubuntu trusty. When launching hubot with (HUBOT_SKYPE_USERNAME and HUBOT_SKYPE_PASSWORD are set):

``` sh
hubot --adapter skype-web
```

I get this output:

```
phantom stdout: NETWORK_ERR: XMLHttpRequest Exception 101: A network error occurred in synchronous requests.

  file:///home/vagrant/hubot/node_modules/phantom/shim.js:7608 in send
  file:///home/vagrant/hubot/node_modules/phantom/shim.js:7608 in _start
  file:///home/vagrant/hubot/node_modules/phantom/shim.js:7635
```

Have you ever encountered such error or know what could be causing it?

EDIT: I have compiled phantomjs 2.0

**Comment by sdimkov** [comment] 2016-01-11 18:06
Hi @patrykziem,

I haven't experienced this issue so far. (I also haven't deployed hubot on Ubuntu)
What I'll write below is just guesswork but I hope it helps you.

The issue seems to be related to cross-domain security of phantomjs's requests. I'm not sure what causes your setup to trigger those errors but we can try the following fix:
1. Open `<your app>/node_modules/hubot-skype-web/src/skypeweb.coffee`
2. Replace the line saying `phantomOptions = {}` with `phantomOptions = parameters: 'web-security': false`

That will hopefully disable CORS Security checks for PhantomJS and resolve your error. I haven't tried it myself.

You can read more at https://github.com/ariya/phantomjs/issues/10985 and [stackoverflow](http://stackoverflow.com/questions/15913170/phantom-js-synchronous-ajax-request-network-err-xmlhttprequest-exception-101)

**Comment by blue-goheimochi** [comment] 2016-02-05 03:04
I had same error.

> 1. Open <code><your app>/node_modules/hubot-skype-web/src/skypeweb.coffee</code>
> 2. Replace the line saying <code>phantomOptions = {}</code> with <code>phantomOptions = parameters: 'web-security': false</code>

Try the above settings , error no longer occurs.
https://github.com/blue-goheimochi/hubot-skype-web/commit/442829ae18a127e68f8b045bebb633fb796e3e46

Perhaps the error was caused by cross-domain policy of PhantomJS.

**Comment by sdimkov** [comment] 2016-02-08 09:35
The CORS fix is released in v0.9.13

**Comment by pziemkowski** [comment] 2016-02-08 10:03
Awesome, I think the issue can be closed now.

**Comment by blue-goheimochi** [comment] 2016-02-08 10:20
Thanks!!

**Closed as completed** 2016-02-08 10:59 UTC
